[pt-BR] SkiptDefaultLib, SkipLib, SourceMap and SourceRoot
microsoft/TypeScript-Website pull request #1021
Opened 2020-09-03 15:37 UTC by juninhogomes

Hello @khaosdoctor, @alvarocamillont, @danilofuchs e @orta

In this PR are the files:

> skipDefaultLibCheck.md
> skipLibCheck.md
> sourceMap.md
> sourceRoot.md

**Some notes about:**

> skipLibCheck.md
 
* I Kept the term `type` in English as in the `exclud.md` file, but in DeclarationDir.md` the term was translated. 

    * I did this because there several files that let terms between backticks on the original language.

* I changed the link to Yarn's resolutions, for the pt-BR version.

____

> sourceMap.md

* Changed the link from Sourcemap Files to the pt-PT version on Mozilla Website. They don't have a pt-Br version yet.

____

> sourceRoot.md

* I used "raiz do código-fonte" for the term "sourceRoot" thinking about what the function does. There other terms that can be used, like "Raiz de origem" or something like this, but I guess that this term fits a little better.  Open to suggestions anyway.

____

And that's it for now. Thank you, guys! 😃

2020-09-03 15:49 UTC, alvarocamillont requested changes

2020-09-03 15:49 UTC, alvarocamillont commented on packages/tsconfig-reference/copy/pt/options/sourceMap.md
> +E isso irá gerar o seguinte mapa json:
E isso irá gerar o seguinte arquivo json do mapa

2020-09-03 15:52 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/sourceMap.md
> +Permite a geração de [mapas de origem](https://developer.mozilla.org/pt-PT/docs/Tools/Debugger/How_to/Use_a_source_map). Esses arquivos permitem a depuradores e outras ferramentas exibir o código fon
```suggestion
Permite a geração de [mapas de origem](https://developer.mozilla.org/pt-PT/docs/Tools/Debugger/How_to/Use_a_source_map). Esses arquivos permitem que depuradores e outras ferramentas exibam o código fonte TypeScript original ao trabalhar com os arquivos JavaScript emitidos. Mapas de origem são emitidos como arquivos `js.map` (ou `jsx.map`) ao lado dos arquivos de saída `.js` correspondentes.
```

2020-09-03 17:28 UTC, juninhogomes commented
@alvarocamillont, @danilofuchs changes in SourceMap made

2020-09-03 17:28 UTC, alvarocamillont approved these changes

2020-09-03 20:05 UTC, danilofuchs commented
LGTM

2020-09-03 20:12 UTC, alvarocamillont commented
LGTM

2020-09-08 15:52 UTC, orta commented
LGTM (I believe I've fixed the action too)

2020-09-08 21:13 UTC, khaosdoctor requested changes
I think you can translate `source map` as `mapas de fonte`

2020-09-08 21:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/sourceMap.md
> +display: "Mapas de origem"
```suggestion
display: "Mapas de fonte"
```

2020-09-08 21:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/sourceMap.md
> +oneline: "Cria mapas de origem para os arquivos JavaScript emitidos"
```suggestion
oneline: "Cria mapas de fonte para os arquivos JavaScript emitidos"
```

2020-09-08 21:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/sourceMap.md
> +Permite a geração de [mapas de origem](https://developer.mozilla.org/pt-PT/docs/Tools/Debugger/How_to/Use_a_source_map). Esses arquivos permitem que depuradores e outras ferramentas exibam o código f
```suggestion
Permite a geração de [mapas de fonte](https://developer.mozilla.org/pt-PT/docs/Tools/Debugger/How_to/Use_a_source_map). Esses arquivos permitem que depuradores e outras ferramentas exibam o código fonte TypeScript original ao trabalhar com os arquivos JavaScript emitidos. Mapas de fonte são emitidos como arquivos `js.map` (ou `jsx.map`) ao lado dos arquivos de saída `.js` correspondentes.
```

2020-09-08 21:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/sourceMap.md
> +Os arquivos `.js` recebem um container com comentários do mapa de origem, indicando para as ferramentas externas onde os arquivos estão. Por exemplo:
```suggestion
Os arquivos `.js` recebem um container com comentários do mapa de fonte, indicando para as ferramentas externas onde os arquivos estão. Por exemplo:
```

2020-09-08 21:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/sourceRoot.md
> +Essa string é processada literalmente dentro do mapa de origem, onde você pode utilizar um caminho ou uma URL:
```suggestion
Essa string é processada literalmente dentro do mapa de fonte, onde você pode utilizar um caminho ou uma URL:
```

2020-09-09 02:21 UTC, danilofuchs commented
> I think you can translate `source map` as `mapas de fonte`
> 
> @danilofuchs @alvarocamillont what do you think?

Personally, I think `mapa de origem` makes a little more sense, although it is inconsistent with other translations.

`source maps` is a term that only exists in this specific context. I think the least we should do is write `mapa de origem (source map)` or `mapa de fonte (source map)` in the `display` or `oneline` attributes

2020-09-09 02:23 UTC, alvarocamillont commented
I like ' mapa de origem" more too

On Tue, Sep 8, 2020 at 11:22 PM Danilo Campana Fuchs <
notifications@github.com> wrote:

> I think you can translate source map as mapas de fonte
>
> @danilofuchs <https://github.com/danilofuchs> @alvarocamillont
> <https://github.com/alvarocamillont> what do you think?
>
> Personally, I think mapa de origem makes a little more sense, although it
> is inconsistent with other translations.
>
> source maps is a term that only exists in this specific context. I think
> the least we should do is write mapa de origem (source map) or mapa de
> fonte (source map) in the display or oneline attributes
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/microsoft/TypeScript-Website/pull/1021#issuecomment-689257237>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AECM4F5D2QG6ZKB5JW2BAILSE3RERANCNFSM4QU5MADQ>
> .
>

2020-09-09 02:47 UTC, khaosdoctor commented
My thinking on this was due to `source code` being translated to `código fonte`, and `source map` using `source` as `origem` and not `fonte`. What about `mapa de código`?

2020-09-10 21:36 UTC, juninhogomes commented
> My thinking on this was due to `source code` being translated to `código fonte`, and `source map` using `source` as `origem` and not `fonte`. What about `mapa de código`?

I like the `mapa de código`, guess that makes sense.

2020-09-17 16:54 UTC, khaosdoctor requested changes
Updated my suggestions

2020-09-21 14:44 UTC, juninhogomes commented
@khaosdoctor Updated

2020-09-26 02:05 UTC, khaosdoctor approved these changes

2020-09-26 02:06 UTC, khaosdoctor commented
lgtm

2020-09-26 02:06 UTC, merged

2020-09-26 02:06 UTC, khaosdoctor commented
With this PR we merged all files in the tsconfig section <3

@orta the tsconfig section is finished