[PT-BR] Import Export.ts, JSDoc Support.ts and Generic Classes.ts
microsoft/TypeScript-Website pull request #1122
Opened 2020-09-22 00:38 UTC by rafaelrozon

Tagging @khaosdoctor, @alvarocamillont, @danilofuchs e @orta  as instructed on https://github.com/microsoft/TypeScript-Website/issues/233.

I have a couple of questions that I would like to clarify:

1. Should the sample code in the Playground docs also be translated or it should remain in English?
2. There're some terms that I'm not sure how to translate and if there is a translation more common in Portuguese. Do you guys follow some convention for technical terms or have a list of technical terms translation from English to Portuguese?

I added a `// !!!!` to where I need to review the translation for some terms. I'll remove those when everyone is happy with the translation.

I'm not sure about these terms:
- named import/export
- logging
- default export
- built-in
- auto-complete

Thank you!

2020-09-23 15:08 UTC, orta commented
1, I generally recommend translating the sample code so that it makes sense to someone without _a lot_ of English context
2, we don't, I'm open to someone making a word list, but it's not something _I_ can do

2020-09-26 01:46 UTC, khaosdoctor commented
About the questions, 1 is like @orta said. We generally recommend the translation of code files because they create context.

On 2, I'll answer all the words here since we still don't have a word list, that's an idea but I hardly think this would be used.

- named import/export => import/export nomeado
- logging -> logging
- default export -> export padrão
- built-in -> nativo
- auto-complete -> auto-complete

2020-09-26 02:02 UTC, khaosdoctor requested changes
Small changes

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// JavaScript adicionou import/export à linguage em 2016
```suggestion
// JavaScript adicionou import/export à linguagem em 2016
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// e TypeScript tem suporte complete para essee estilo de
```suggestion
// e TypeScript tem suporte completo para esse estilo de
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// TypeScript expande essa sintaxe ao permitir que tipos
```suggestion
// O TypeScript expande essa sintaxe ao permitir que tipos
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// TypeScript permite que engenheiros documentem seus códigos usando
```suggestion
// O TypeScript permite que engenheiros documentem seus códigos usando
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Se você quiser saber como criar essa anotações de documentação
```suggestion
// Se você quiser saber como criar essas anotações de documentação
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// padråo de um módulo. Um exemplo disso é o módulo debug, o qual
```suggestion
// padrão de um módulo. Um exemplo disso é o módulo debug, o qual
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// !!!!!
```suggestion

```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// expõe uma funcão que cria uma função de log.
```suggestion
// expõe uma função que cria uma função de log.
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// !!!!!
```suggestion

```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Estes não são os únicoss tipos de importação, apenas os
```suggestion
// Estes não são os únicos tipos de importação, apenas os
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Isso define a propriedade default no objeto exports como
```suggestion
// Isso define a propriedade padrão no objeto exports como
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// TypeScript optou por utilizar a especificação ECMAScript
```suggestion
// O TypeScript optou por utilizar a especificação ECMAScript
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// sobre como lidar com esses casos, que é criar um error.
```suggestion
// sobre como lidar com esses casos, que é criar um erro.
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// automaticamente com esses casos para você, a qual é a esModuleInterop.
```suggestion
// automaticamente com esses casos para você, que é a esModuleInterop.
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Se você ativar ela nessa exemplo, você verá que o erro desaparece.
```suggestion
// Se você ativar ela nesse exemplo, você verá que o erro desaparece.
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// TypeScript tem um suporte muito rico de JSDoc, para muitos casos
```suggestion
// TypeScript tem um suporte muito rico ao JSDoc, para muitos casos
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// você pode até não utilizar arquivos .ts e apenas usar annotações de JSDoc
```suggestion
// você pode até não utilizar arquivos .ts e apenas usar anotações de JSDoc
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// Um comentário JSDoc é um comentário de multiplas linhas que
```suggestion
// Um comentário JSDoc é um comentário de múltiplas linhas que 
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// Comentáios JSDoc são um meio de fornecer informação sobre os tipos utilizados
```suggestion
// Comentários JSDoc são um meio de fornecer informação sobre os tipos utilizados
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// para o TypesScript e editores. Vamos começar com um fácil,
```suggestion
// para o TypeScript e editores. Vamos começar com um fácil,
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// !!!!
```suggestion

```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// Extendendo globais em JSDoc é um processo mais envolvente
```suggestion
// Estender globais em JSDoc é um processo mais complicado
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// o qual você pode conferir no manual do VS Code:
```suggestion
// que você pode conferir no manual do VS Code:
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
> +// Este exemplo é em sua maioria em TypeScript, porque é um modo muito
```suggestion
// Este exemplo é, em sua maioria, em TypeScript, porque é um modo muito
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
> +// Para user uma Gaveta você precisará trabalhar com outro tipo:
```suggestion
// Para usar uma Gaveta você precisará trabalhar com outro tipo:
```

2020-09-26 02:02 UTC, khaosdoctor commented on packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
> +// requer o uso da etiqueta chamada template (template tag) em JSDoc.
```suggestion
// requer o uso da tag "template" em JSDoc.
```

2020-10-04 00:43 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
> +// requer o uso da etiqueta chamada template (template tag) em JSDoc.
Fixed.

2020-10-04 00:43 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
> +// Para user uma Gaveta você precisará trabalhar com outro tipo:
Fixed.

2020-10-04 00:43 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Working With Classes/Generic Classes.ts
> +// Este exemplo é em sua maioria em TypeScript, porque é um modo muito
Fixed.

2020-10-04 00:49 UTC, rafaelrozon reviewed
Thank you @khaosdoctor and @orta  for the review. I addressed all the comments and did some small changes. Let me know if there's anything else that needs a fix. 

Thanks!

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// o qual você pode conferir no manual do VS Code:
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// Extendendo globais em JSDoc é um processo mais envolvente
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// !!!!
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// para o TypesScript e editores. Vamos começar com um fácil,
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// Comentáios JSDoc são um meio de fornecer informação sobre os tipos utilizados
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// Um comentário JSDoc é um comentário de multiplas linhas que
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// você pode até não utilizar arquivos .ts e apenas usar annotações de JSDoc
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/JSDoc Support.js
> +// TypeScript tem um suporte muito rico de JSDoc, para muitos casos
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Se você ativar ela nessa exemplo, você verá que o erro desaparece.
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// automaticamente com esses casos para você, a qual é a esModuleInterop.
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// sobre como lidar com esses casos, que é criar um error.
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// TypeScript optou por utilizar a especificação ECMAScript
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Isso define a propriedade default no objeto exports como
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Estes não são os únicoss tipos de importação, apenas os
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// !!!!!
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// expõe uma funcão que cria uma função de log.
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// padråo de um módulo. Um exemplo disso é o módulo debug, o qual
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// !!!!!
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// Se você quiser saber como criar essa anotações de documentação
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// TypeScript permite que engenheiros documentem seus códigos usando
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// TypeScript expande essa sintaxe ao permitir que tipos
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// e TypeScript tem suporte complete para essee estilo de
Fixed.

2020-10-04 00:49 UTC, rafaelrozon commented on packages/playground-examples/copy/pt/JavaScript/Modern JavaScript/Import Export.ts
> +// JavaScript adicionou import/export à linguage em 2016
Fixed.

2020-10-06 17:40 UTC, khaosdoctor commented
I guess that'd be all! Thanks for the PR :D

2020-10-06 17:40 UTC, khaosdoctor approved these changes

2020-10-06 17:40 UTC, khaosdoctor commented
lgtm

2020-10-06 17:41 UTC, merged

2020-10-06 18:01 UTC, rafaelrozon commented
Thanks, Lucas and Orta for reviewing it.