docs(i18n-id): Translate out.md until outFile.md into indonesian
microsoft/TypeScript-Website pull request #1229
Opened 2020-10-09 18:50 UTC by 0length

## Overview
This is part of #938 

## Changes
Translate for files:
- [x] out.md
- [x] outDir.md
- [x] outFile.md

2020-10-10 20:37 UTC, mandaputtra approved these changes
Sudah Bagus :+1: :100:

2020-10-11 15:38 UTC, jefrydco approved these changes

2020-10-11 16:07 UTC, mazipan requested changes

2020-10-11 16:07 UTC, mazipan commented on packages/tsconfig-reference/copy/id/options/outDir.md
> +
folder: direktori

2020-10-11 17:01 UTC, 0length commented on packages/tsconfig-reference/copy/id/options/outDir.md
> +
done

2020-10-12 05:49 UTC, mazipan approved these changes
LGTM 🎉

2020-10-12 06:51 UTC, mandaputtra commented
Sepertinya botnya kalau di LGTM lewat komemtar approve ga nyaut dia,

2020-10-12 06:51 UTC, merged