fiqriachmada
microsoft/TypeScript-Website pull request #1245
Opened 2020-10-15 14:01 UTC by fiqriachmada

I been contributing on exclude.md in Bahasa Indonesia. Thanks for merge mine.

2020-10-15 14:04 UTC, fiqriachmada commented
> Thanks for the PR!
> 
> This section of the codebase is owned by @jefrydco, @nusendra, @mazipan, and @mandaputtra - if they write a comment saying "LGTM" then it will be merged.

I been sign the lisence

2020-10-15 14:20 UTC, jefrydco commented
Mas @fiqriachmada , minta tolong judul Pull Requestnya diubah dengan format kurang lebih seperti ini ya
```
docs(i18n-id): translate <something> and <something> into Indonesian
````

Sama bagian deskripsinya menjadi
```
Overview
This is a part of #938

Changes
Provides Indonesia translation for:

- [ ]  <nama-berkas>
- [ ]  <nama-berkas>
- [ ]  ...
```

2020-10-15 14:23 UTC, jefrydco requested changes
Minta tolong komentar bahasa Inggris nya dihapus

2020-10-15 14:26 UTC, jefrydco requested changes

2020-10-15 14:26 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/exclude.md
> +Sebuah berkas yang ditentukan oleh `exclude` masih bisa menjadi bagian dari basis kode Anda dikarenakan pernyataan `import` di dalam kode Anda, penyertaan sebuah `types`, sebuah arahan `/// <referenc
`arahan` ini sepertinya lebih baik tidak diterjemahkan karena istilah teknis dalam TypeScript

2020-10-15 14:26 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/exclude.md
> +Ini bukan sebuah mekanisme yang **mencegah** sebuah berkas yang disertakan dalam basis kode - ini semudah mengubah apa yang pengaturan `include` temukan.
Mungkin bisa diperjelas `ini` itu mengarah ke mana. Kalau dilihat dari konteksnya, sepertinya `ini` itu mengarah ke `exclude`. Jadi mungkin bisa diubah kalimatnya menjadi
```
`exclude` bukan sebuah mekanisme... - `exclude` mengubah apa yang...
```

2020-10-24 12:53 UTC, mandaputtra requested changes
Feedback sama seperti mas @jefrydco ya

2020-10-31 01:57 UTC, mandaputtra commented
Already translated well. Hi @orta help me close this.

2020-10-31 10:09 UTC, orta commented
👍🏻

2020-10-31 10:09 UTC, closed without merging