docs(i18n-id): Provide Indonesian translation for documentation
microsoft/TypeScript-Website pull request #1253
Opened 2020-10-18 15:08 UTC by xen0m29

**Overview**
Refer to #938 and [this comment](https://github.com/microsoft/TypeScript-Website/issues/938#issuecomment-706573677), I translated the files into Indonesian.

**Changes**
Provides Indonesian translation for the following files:

- [x] Nightly Builds.md
- [x] Creating DTS files From JS.md
- [x] Intro to JS with TS.md
- [x] JSDoc Reference.md
- [x] Configuring Watch.md
- [x] Decorators.md
- [x] Iterators and Generators.md
- [x] JSX.md
- [x] Mixins.md
- [x] Symbols.md
- [x] Babel with TypeScript.md
- [x] DOM Manipulation.md
- [x] React.md
- [x] TypeScript Tooling in 5 minutes.md

2020-10-19 13:08 UTC, mandaputtra commented
Wow banyak sekali ~ haha Terimakasih @xen0m29. Tapi besok kalau PR lagi tolong dibagi menjadi beberapa PR saja ya, 1 - 3 file saja kasihan yang review :rofl: :smile:

2020-10-19 13:09 UTC, mandaputtra requested changes
disini ada lock filenya tolong di hilangkan dulu perubahan di lockfile, karena kalau ada lock file tidak bisa otomatis di merge oleh team reviewer Indonesia

2020-10-20 11:52 UTC, xen0m29 commented
> Wow banyak sekali ~ haha Terimakasih @xen0m29. Tapi besok kalau PR lagi tolong dibagi menjadi beberapa PR saja ya, 1 - 3 file saja kasihan yang review 🤣 😄

hahaha siap

2020-10-20 11:53 UTC, xen0m29 commented
> disini ada lock filenya tolong di hilangkan dulu perubahan di lockfile, karena kalau ada lock file tidak bisa otomatis di merge oleh team reviewer Indonesia

baik, sudah saya hapus

2020-10-20 14:01 UTC, mandaputtra commented
@xen0m29 bisa di close dan bikin PR lagi saja? sepertinya bot auto merge-nya tidak ter trigger

2020-10-20 14:28 UTC, xen0m29 commented
> @xen0m29 bisa di close dan bikin PR lagi saja? sepertinya bot auto merge-nya tidak ter trigger

baiklah @mandaputtra

2020-10-20 14:28 UTC, closed without merging