Update TS for Functional Programmers.md
microsoft/TypeScript-Website pull request #1309
Opened 2020-10-31 10:53 UTC by molaux

As the comment suggests, `snd` should be just a more precise declaration of the preceding statement `fst`, isn't it ?

2020-11-01 16:03 UTC, orta commented
I agree /cc @sandersn just to triple check

2020-11-02 19:18 UTC, sandersn requested changes
The code is written as intended.

However, maybe my intention was confusing. My assumption was that `fst` and `snd` are such a linked pair that I could use them as a single example: showing the imprecise type for `fst` and the precise one for `snd` would flow pretty much the same as rewriting the type of `fst` to be more precise.

Maybe it would be clearer to rewrite `fst`. The example will produce an error then, but I'm not sure we're running the compiler on these documents anyway. Are we, @orta?

Edit: Oops, I meant to say: rewrite `snd` &rarr; `fst`.

2020-11-02 19:20 UTC, orta commented
We can!

2020-11-02 20:29 UTC, DanielRosenwasser commented
"more precisely" implies you're not going to switch to a different function, the change + switching to `fst` sounds good.

2020-11-02 20:31 UTC, merged