docs(i18n-id): translate extends.md to forceConsistentCasingInFileNames.md and several config section into Indonesia
microsoft/TypeScript-Website pull request #1338
Opened 2020-11-14 12:40 UTC by R1dwanMaulana

## Overview

this is part of #938 

## Changes
translate the following files
- [x] extends.md
- [x] fallbackPolling.md
- [x] files.md
- [x] forceConsistentCasingInFilesNames.md

2020-12-15 10:18 UTC, jefrydco requested changes
Hi Mas @R1dwanMaulana , sorry ya, it takes us quite long time to get back reviewing this PR. 🙏

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Perlu diperhatikan bahwa `files`,` include` dan `exclude` dari berkas konfigurasi yang mewarisi _overwrite_ yang berasal dari
"konfigurasi yang mewarisi _overwrite_ yang berasal.." mungkin bisa diterjemahkan menjadi "konfigurasi yang menimpa yang berasal dari".

Kalau konteks bahasa Inggrisnya gimana Mas? @R1dwanMaulana

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Saat ini, satu-satunya properti tingkat atas yang dikecualikan dari warisan adalah [`referensi`](#references).
`dari warisan` -> `dari pewarisan`

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Properti dengan jalur relatif yang ditemukan di berkas konfigurasi, yang tidak dikecualikan dari warisan, akan diselesaikan secara relatif terhadap berkas konfigurasi tempat asalnya.
`warisan` -> `pewarisan`, minta tolong dicek yang lainnya juga ya Mas

`diselesaikan` -> `diresolusikan (_resolve_)`, sepertinya konteks bahasa inggrisnya `resolve` kan ya?

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/fallbackPolling.md
> +Saat menggunakan peristiwa sistem berkas, opsi ini menetapkan strategi polling yang akan digunakan saat sistem kehabisan pengamat berkas asli dan / atau tidak mendukung pengamat berkas asli.
`polling` -> `_polling_`

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/fallbackPolling.md
> +- `synchronousWatchDirectory`: Menonaktifkan tontonan yang ditunda pada direktori. Menonton yang ditunda berguna ketika banyak perubahan berkas mungkin terjadi sekaligus (misal. Perubahan dalam `node
Di bagian atasnya `tontonan` menggunakan kata `pengawas`

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/forceConsistentCasingInFileNames.md
> +Ini bisa menjadi masalah jika beberapa pengembang bekerja dalam sistem berkas case-sensitive dan yang lainnya tidak.
`case-sensitive` -> `sensitifitas huruf besar dan kecil`, sepertinya di bagian sebelumnya sudah diterjemahkan

2020-12-15 10:18 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/forceConsistentCasingInFileNames.md
> +Ketika opsi ini disetel, TypeScript akan mengeluarkan kesalahan jika program mencoba memasukkan berkas dengan casing yang berbeda dari casing pada disk.
`kesalahan` -> `galat`
`casing` -> `jenis huruf`, kayaknya ini konteksnya antara huruf besar dan huruf kecil

2020-12-15 23:46 UTC, R1dwanMaulana commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Perlu diperhatikan bahwa `files`,` include` dan `exclude` dari berkas konfigurasi yang mewarisi _overwrite_ yang berasal dari
_the inheriting config file _overwrite_ those from_

2020-12-15 23:48 UTC, R1dwanMaulana commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Properti dengan jalur relatif yang ditemukan di berkas konfigurasi, yang tidak dikecualikan dari warisan, akan diselesaikan secara relatif terhadap berkas konfigurasi tempat asalnya.
iya mas `resolved`

2020-12-16 03:07 UTC, jefrydco commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Perlu diperhatikan bahwa `files`,` include` dan `exclude` dari berkas konfigurasi yang mewarisi _overwrite_ yang berasal dari
Ah, mungkin bisa menjadi `dari berkas konfigurasi pewaris menimpa konfigurasi yang berasal dari berkas konfigurasi asal`

2020-12-16 04:08 UTC, R1dwanMaulana commented on packages/tsconfig-reference/copy/id/options/extends.md
> +Perlu diperhatikan bahwa `files`,` include` dan `exclude` dari berkas konfigurasi yang mewarisi _overwrite_ yang berasal dari
ok noted

2020-12-17 12:26 UTC, mandaputtra approved these changes

2020-12-18 02:16 UTC, jefrydco commented
LGTM

2020-12-18 02:16 UTC, merged

2020-12-18 02:17 UTC, jefrydco approved these changes