[PT-BR] Translating JSDoc Reference, Configuring Watch, Project References and Declaration Merging
microsoft/TypeScript-Website pull request #1384
Opened 2020-11-30 17:21 UTC by luk3skyw4lker

Translating 3 files and fixing Creating DTS Files from JavaScript being on wrong directory.

2020-11-30 19:19 UTC, luk3skyw4lker commented
@khaosdoctor @danilofuchs @orta 

I couldn't add you as reviewers (the option doesn't appear on my browser) so I'm mentioning you guys here. Thanks!

2020-12-02 23:16 UTC, khaosdoctor requested changes

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Configuring Watch.md
> +`fs.watch` usa os eventos do file system para notificar as mudanças no arquivo/diretório. Mas isso depende do SO e a notificação não é completamente confiável e não funciona como esperado em vários S
```suggestion
`fs.watch` usa os eventos do file system para notificar as mudanças no arquivo/diretório. Mas isso depende do SO e a notificação não é completamente confiável e não funciona como esperado em vários SOs. Também pode haver um limite do número de observadores que podem ser criados, eg. linux, e nós poderíamos superar esse limite bem rápido com programas que incluem grandes números de arquivos. Mas, por usar os eventos do file system, não há tantos ciclos de CPU envolvidos. O compilador usa `fs.watch` tipicamente para observar diretórios (eg. diretórios fonte que são incluídos por um arquivo de configuração, diretório em que a resolução de módulos falhou etc.) estes podem lidar com a falta de precisão em notificação de mudanças. Mas observação recursiva é suportada apenas no Windows e no OSX. Isso significa que precisamos de algo para substituir a natureza recursiva em outros SOs.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Configuring Watch.md
> +Você pode ler mais sobre isso nas [notas de lançamento](/docs/handbook/release-notes/typescript-3-8.html#better-directory-watching-on-linux-and-watchoptions).
```suggestion
Você pode ler mais sobre isso nas [notas de atualização](/docs/handbook/release-notes/typescript-3-8.html#better-directory-watching-on-linux-and-watchoptions).
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Configuring Watch.md
> +`UseFsEvents`                                  | Usa o `fs.watch` que por sua vez usa os eventos de file system (mas pode não ser exato em diferentes SO) para conseguir as notificações de mudança/cri
```suggestion
`UseFsEvents`                                  | Usa o `fs.watch` que por sua vez usa os eventos de file system (mas pode não ser exato em diferentes SOs) para conseguir as notificações de mudança/criação/remoção de arquivos. Note que alguns SOs eg. linux tem um limite no número de observadores e a falha de criação de um observador com `fs.watch` resultará na criação de outro observador usando `fs.watchFile`
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Configuring Watch.md
> +A observação de diretório em plataformas que não suportam observação recursiva de diretório nativamente em node, é suportada por meio da criação recursiva de observadores de diretório para os diretór
```suggestion
A observação de diretório em plataformas que não suportam observação recursiva de diretório nativamente em node é suportada por meio da criação recursiva de observadores de diretório para os diretórios filhos usando diferentes opções selecionadas pela variável ambiente `TSC_WATCHDIRECTORY`. Note que, em plataformas que suportam observação de diretórios recursivamente (e.g. windows), o valor dessa variável é ignorado.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +Fazendo isso, você pode melhorar muito tempos de compilação, garantir serparação lógica entre componentes e organizar seu código de melhores maneiras.
```suggestion
Fazendo isso, você pode melhorar muito tempos de compilação, garantir separação lógica entre componentes e organizar seu código de melhores maneiras.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +- Invoking `tsc` twice incurs more startup time overhead
```suggestion

```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +- Invocar `tsc` duas vezes implicaria em mais sobrecarga de tempo de início
```suggestion
- Invocar `tsc` duas vezes implicaria em mais sobrecarga no tempo de inicialização
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +Enabling the `composite` flag changes a few things:
```suggestion

```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +## `declarationMap`s
```suggestion
## `declarationMap`
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +Se você habilitar `--declarationMap`, você será capaz de usar funcionalidades de editores tais como "Ir para definição" e Renomear para transparentemente navegar e editar código entre limites de proj
```suggestion
Se você habilitar `--declarationMap`, você será capaz de usar funcionalidades de editores tais como "Ir para definição" e Renomear para transparentemente navegar e editar código entre projetos em editores que são suportados.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +Você também pode habilitar a pre-adição de saídas de uma dependência usando a opção `prepend` em uma referência:
```suggestion
Você também pode habilitar a prefixação de saídas de uma dependência usando a opção `prepend` em uma referência:
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +Pré-adicionar um projeto vai incluir a saída dele acima da saída do projeto atual.
```suggestion
Prefixar um projeto vai incluir a saída dele acima da saída do projeto atual.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +É importante nessa situação que não seja realizada a pré-adição em cada referência, porque você vai acabar tendo duas cópias de `A` na saída de `D` - isso pode levar a resultados inesperados.
```suggestion
É importante nessa situação que não seja realizada a prefixação em cada referência, porque você vai acabar tendo duas cópias de `A` na saída de `D` - isso pode levar a resultados inesperados.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +If you check in any build outputs (`.js`, `.d.ts`, `.d.ts.map`, etc.), you may need to run a `--force` build after certain source control operations depending on whether your source control tool pres
Missing translation here

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/project-config/Project References.md
> +ao seu arquivo proj. Isso vai habilitar compilação incremental e limpeza automáticas.
```suggestion
Ao seu arquivo proj. Isso vai habilitar compilação incremental e limpeza automáticas.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/reference/Declaration Merging.md
> +Alguns dos conceitos únicos em Typescript descreve a forma de um objeto Javascript ao nível de tipo.
```suggestion
Alguns dos conceitos únicos em Typescript descrevem a forma de um objeto Javascript ao nível de tipo.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/reference/Declaration Merging.md
> +Um exemplo que é especialmente único do Typescript é o coneito de 'fusão de declarações'.
```suggestion
Um exemplo que é especialmente único do Typescript é o conceito de 'fusão de declarações'.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/reference/Declaration Merging.md
> +Similar às interfaces, namespaces de mesmo nome serão também fundir seus membros.
```suggestion
Similar às interfaces, namespaces de mesmo nome terão seus membros fundidos.
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/reference/Declaration Merging.md
> +    return haveMuscles; // Error, because haveMuscles is not accessible here
```suggestion
    return haveMuscles; // Erro, porque haveMuscles não é acessível aqui
```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/reference/Declaration Merging.md
> +## Merging Namespaces with Classes, Functions, and Enums
```suggestion

```

2020-12-02 23:16 UTC, khaosdoctor commented on packages/documentation/copy/pt/reference/Declaration Merging.md
> +Olhemos para um exemplo de brinquedo de Observable:
```suggestion
Olhemos para um exemplo de Observable:
```

2020-12-03 17:48 UTC, luk3skyw4lker commented
Sorry for the dummy errors, it was my first time contributing in an open source project and it was long since I've last translated something from English into Portuguese hahaha

2020-12-11 17:39 UTC, khaosdoctor commented
No worries! I'll merge it and verify using local editors :)

2020-12-11 17:39 UTC, khaosdoctor commented
lgtm

2020-12-11 17:40 UTC, merged