Added TS4.8 release notes
microsoft/TypeScript-Website pull request #2544
Opened 2022-09-26 16:51 UTC by navya9singh

2022-09-26 16:55 UTC, andrewbranch requested changes

2022-09-26 16:55 UTC, andrewbranch commented on packages/documentation/copy/en/release-notes/Typescript 4.8.md
> +These breaks are now detailed in our [Correctness Fixes and Breaking Changes section](#correctness-changes)
This section should be removed

2022-09-26 16:55 UTC, andrewbranch commented on packages/documentation/copy/en/release-notes/Typescript 4.8.md
> +## <a name="smarter-type-narrowing-and-simplifications"></a> Improved Intersection Reduction, Union Compatibility, and Narrowing
All the empty anchors in headings need to be removed

2022-09-26 17:14 UTC, navya9singh commented on packages/documentation/copy/en/release-notes/Typescript 4.8.md
> +These breaks are now detailed in our [Correctness Fixes and Breaking Changes section](#correctness-changes)
There are similar 'What's New Since the Beta and RC' sections in 4.6.md and 4.5.md. Should I remove them?

2022-09-26 22:08 UTC, andrewbranch approved these changes

2022-09-26 22:09 UTC, andrewbranch commented on packages/documentation/copy/en/release-notes/Typescript 4.8.md
> +These breaks are now detailed in our [Correctness Fixes and Breaking Changes section](#correctness-changes)
Sure!

2022-09-27 16:32 UTC, andrewbranch approved these changes

2022-09-27 17:06 UTC, merged