Update Decorators.md - Fix TypedDescriptor error
microsoft/TypeScript-Website pull request #2579
Opened 2022-10-23 18:09 UTC by gjuoun

In this PR

* Fix the `descripor.value` type in the chapter `Decorator`.

<img width="885" alt="image" src="https://user-images.githubusercontent.com/8935612/197407573-40d73ce0-4686-417d-8613-d451b7147be0.png">

2022-10-24 14:02 UTC, hexiaokang approved these changes

2023-05-18 23:04 UTC, jakebailey commented on packages/documentation/copy/en/reference/Decorators.md
> +function validate(target: any, propertyName: string, descriptor: TypedPropertyDescriptor<AnyFunction>) {
Honestly, I would just use `any` here, as that matches the previous code box. These docs will become less and less relevant anyway given ECMAScript decorators are now a part of TypeScript.

2023-07-24 21:21 UTC, jakebailey commented
Checking again, this code appears to work in the playground; have I missed something?

https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true#code/JYWwDg9gTgLgBAIigUwGYBtkGMYFoTIwCGAJkcQgNwCwAUFhAHYDO8KAjgK7AokCyhUuSIBpZAE84AXjgBlcSABGEdAAokyLj2QkEAShq06qToxzAmcDt16riUAOaEAXHADyigFbYYAGjhgUBBgyLDiYuKurFDAjA5wAD5wzArK6P5gRFBEBDChAJKMJMgAHq6MnEqhenAA3nRwcJjwpcCssQ4ASpo2OgAKWTmEoczllYqhANoAutJw3Rg+AHROMG4A7owCxGTEqtba-IK7ohL+9qsZQSFhETUJSTOGja3tcd1avAPZuSNLYJxmAALVSZH7DKCFYolAwNeZoTA4JbFVCxZDbIR7Kw9Q4Yk4RfyvGAdD69EjfIZ5KDMc5ZS4Ba6hGDhCSw2gAXzoxlM5ksADciOhgLtkHY6S44ERGOIrsEmeIAHJDKIwGJxfzFZhYGJgGDQVwAFXEIXJjLCABFkFqdXqoAAeABiPOJTAAfDV6rRGs04LkgRASHNNdrgLroEsBehOMgAISGOHBm3hyPRuYmMwuxhwVQeuHewjYz79Qa-aljKpQGZzBaImArQgbLbHYT7HG8PHCAlwC6EWU3ZlKghsxqNYCobMHL4liHMXNekeNVDQbM+sGUgpFUpwCDjyfF8FU2d1PMLuBj7Nr0tQreumR0yrIRgwZhLTBxGBAxJJe8EJ-MSaXhC14lLMUhgXApgomiJBzqep4fkE6xwIwyBIQAolAQRQOofBtMwHSFmSkqOA+T5LPozxwXAnLzguNF0SeKAwJwUBZn6AZLEQYBgOg4h2ECbT+D+j7PsO1GGOyQA

2023-07-24 21:22 UTC, jakebailey requested changes
Checking again, this code appears to work in the playground; have I missed something?

[Playground Link](https://www.typescriptlang.org/play?experimentalDecorators=true&emitDecoratorMetadata=true#code/JYWwDg9gTgLgBAIigUwGYBtkGMYFoTIwCGAJkcQgNwCwAUFhAHYDO8KAjgK7AokCyhUuSIBpZAE84AXjgBlcSABGEdAAokyLj2QkEAShq06qToxzAmcDt16riUAOaEAXHADyigFbYYAGjhgUBBgyLDiYuKurFDAjA5wAD5wzArK6P5gRFBEBDChAJKMJMgAHq6MnEqhenAA3nRwcJjwpcCssQ4ASpo2OgAKWTmEoczllYqhANoAutJw3Rg+AHROMG4A7owCxGTEqtba-IK7ohL+9qsZQSFhETUJSTOGja3tcd1avAPZuSNLYJxmAALVSZH7DKCFYolAwNeZoTA4JbFVCxZDbIR7Kw9Q4Yk4RfyvGAdD69EjfIZ5KDMc5ZS4Ba6hGDhCSw2gAXzoxlM5ksADciOhgLtkHY6S44ERGOIrsEmeIAHJDKIwGJxfzFZhYGJgGDQVwAFXEIXJjLCABFkFqdXqoAAeABiPOJTAAfDV6rRGs04LkgRASHNNdrgLroEsBehOMgAISGOHBm3hyPRuYmMwuxhwVQeuHewjYz79Qa-aljKpQGZzBaImArQgbLbHYT7HG8PHCAlwC6EWU3ZlKghsxqNYCobMHL4liHMXNekeNVDQbM+sGUgpFUpwCDjyfF8FU2d1PMLuBj7Nr0tQreumR0yrIRgwZhLTBxGBAxJJe8EJ-MSaXhC14lLMUhgXApgomiJBzqep4fkE6xwIwyBIQAolAQRQOofBtMwHSFmSkqOA+T5LPozxwXAnLzguNF0SeKAwJwUBZn6AZLEQYBgOg4h2ECbT+D+j7PsO1GGOyQA)

2024-06-02 19:01 UTC, closed without merging