Update Narrowing.md
microsoft/TypeScript-Website pull request #2849
Opened 2023-06-03 00:16 UTC by dnamkoong

The first example under `Exhaustiveness checking` should not raise an error

2023-06-05 17:02 UTC, jakebailey requested changes

2023-06-05 17:02 UTC, jakebailey commented on packages/documentation/copy/en/handbook-v2/Narrowing.md
> +For example, adding a `default` to our `getArea` function which tries to assign the shape to `never` will not raise an error when every possible case has not been handled.
This isn't right; the word `not` already appears later in the sentence ("when every possible case has not been handled").

But, I think it may be worth moving `not` forward to where you have it now and drop the second not. That way the fact that there's no error is right up front.

2023-06-05 17:06 UTC, dnamkoong commented on packages/documentation/copy/en/handbook-v2/Narrowing.md
> +For example, adding a `default` to our `getArea` function which tries to assign the shape to `never` will not raise an error when every possible case has not been handled.
Sounds good

2023-06-20 18:00 UTC, jakebailey commented on packages/documentation/copy/en/handbook-v2/Narrowing.md
> +For example, adding a `default` to our `getArea` function which tries to assign the shape to `never` will not raise an error when every possible case has not been handled.
You closed this and pinged me for a review, but haven't updated the PR; is there a change you have forgotten to push to address the above?

2023-06-21 17:30 UTC, dnamkoong commented on packages/documentation/copy/en/handbook-v2/Narrowing.md
> +For example, adding a `default` to our `getArea` function which tries to assign the shape to `never` will not raise an error when every possible case has not been handled.
Thought I updated the PR, change has been pushed

2023-06-21 17:33 UTC, jakebailey approved these changes

2023-06-21 17:56 UTC, merged