Fix typo in TypeScript 2.2.md
microsoft/TypeScript-Website pull request #3033
Opened 2024-02-18 08:41 UTC by eugeneilyin

2024-02-18 09:31 UTC, eugeneilyin commented
@microsoft-github-policy-service agree

2024-03-29 23:24 UTC, jakebailey requested changes

2024-03-29 23:24 UTC, jakebailey commented on packages/documentation/copy/en/release-notes/TypeScript 2.0.md
>  A class with protected constructor cannot be instantiated outside the class body, but can be extended.
```suggestion
A class with a protected constructor cannot be instantiated outside the class body, but can be extended.
```

2024-03-29 23:24 UTC, jakebailey commented on packages/documentation/copy/en/release-notes/TypeScript 4.1.md
> +Many users take advantage of this to spread properties "conditionally".
This one isn't wrong; it's "spreading in" props to something else.

2024-06-02 08:58 UTC, eugeneilyin reviewed
LGTM

2024-06-05 17:53 UTC, jakebailey approved these changes

2024-09-30 18:30 UTC, jakebailey approved these changes

2024-09-30 18:57 UTC, merged