[pt-br] translating tsconfig-reference options files, related to module resolution
microsoft/TypeScript-Website pull request #837
Opened 2020-08-02 17:05 UTC by Leonardogrtt

Files:
- esModuleInterop.md
- moduleResolution.md
- paths.md
- preserveSymlinks.md
- typeRoots.md
- types.md

reference: #233

🦖

2020-08-02 21:02 UTC, danilofuchs approved these changes
LGTM!

2020-08-02 21:02 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/paths.md
> +Uma série de entradas que remapeiam as importações para locais de pesquisa relativos à `baseUrl`, há uma cobertura mais abrangente de `paths` no [handbook](/docs/handbook/module-resolution.html#path-
```suggestion
Uma série de entradas que remapeiam as importações para locais de pesquisa relativos à `baseUrl`, há uma cobertura mais abrangente de `paths` no [manual](/docs/handbook/module-resolution.html#path-mapping).
```

Não sei se vamos deixar como Handbook ou vamos traduzir para Manual. O que acha, @khaosdoctor?

2020-08-03 20:12 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/paths.md
> +Uma série de entradas que remapeiam as importações para locais de pesquisa relativos à `baseUrl`, há uma cobertura mais abrangente de `paths` no [handbook](/docs/handbook/module-resolution.html#path-
Eu acho que podemos traduzir para manual... Porque é realmente uma palavra que podemos adicionar sem mudar muita coisa

2020-08-03 20:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +Permite interoperabilidade de emição entre Módulos CommonJS e ES através da criação de objetos namespace para todas as importações.
```suggestion
Permite interoperabilidade de emição entre Módulos CommonJS e ES através da criação de namespaces para todas as importações.
```

2020-08-03 20:13 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +Este padrão de exportação é raro em módulos para CommonJS. Por exemplo, sem `esModuleInterop` como true:
```suggestion
TypeScript adere ao padrão EcmaScript para módulos, o que significa que um arquivo com exportações teria que especificamente incluir uma exportação `default` para dar suporte à sintaxes como `import React from "react"`.
Este padrão de exportação é raro em módulos para CommonJS. Por exemplo, sem `esModuleInterop` como true:
```

2020-08-03 20:14 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +const getStringLength = (str) => str.length;
```suggestion
const obterTamanhoDaString = (str) => str.length;
```

2020-08-03 20:15 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +  getStringLength,
```suggestion
  obterTamanhoDaString,
```

2020-08-03 20:15 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +// @filename: utilFunctions.js
```suggestion
// @filename: utilitarios.js
```

2020-08-03 20:15 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +import utils from "./utilFunctions";
```suggestion
import utils from "./utilitarios";
```

2020-08-03 20:16 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +const count = utils.getStringLength("Check JS");
```suggestion
const count = utils.obterTamanhoDaString("Checagem JS");
```

2020-08-03 20:17 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +// @filename: utilFunctions.js
```suggestion
// @filename: utilitarios.js
```

2020-08-03 20:17 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +const getStringLength = (str) => str.length;
```suggestion
const obterTamanhoDaString = (str) => str.length;
```

2020-08-03 20:17 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +const allFunctions = {
```suggestion
const todasAsFuncoes = {
```

2020-08-03 20:17 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +module.exports = allFunctions;
```suggestion
const todasAsFuncoes = {
  obterTamanhoDaString,
};

module.exports = todasAsFuncoes;
```

2020-08-03 20:18 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/esModuleInterop.md
> +Ativando esta flag no compilador também vai habilitar [`allowSyntheticDefaultImports`](#allowSyntheticDefaultImports).
```suggestion
Ativando esta flag no compilador, a opção [`allowSyntheticDefaultImports`](#allowSyntheticDefaultImports) também será habilitada.
```

2020-08-03 20:18 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/moduleResolution.md
> +oneline: "Permite estratégias de resolução de módulos TypeScript 1.6"
```suggestion
oneline: "Permite a especificação de estratégias de resolução de módulos TypeScript 1.6"
```

2020-08-03 20:18 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/moduleResolution.md
> +Especifica a estratégia de resolução de módulos: `'node'` (Node.js) ou `classic` (utilizada no TypeScript antes da versão 1.6).
```suggestion
Especifica a estratégia de resolução de módulos: `node` (Node.js) ou `classic` (utilizada no TypeScript antes da versão 1.6).
```

2020-08-03 20:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/moduleResolution.md
> +Você provavelmente não vai precisar utilizar `classic` em código atual.
```suggestion
Você provavelmente não vai precisar utilizar `classic` em código mais recente.
```

2020-08-03 20:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/moduleResolution.md
> +Há uma página de referência em [Resolução de Módulos](/docs/handbook/module-resolution.html)
```suggestion
Veja a página de referência em: [Resolução de Módulos](/docs/handbook/module-resolution.html)
```

2020-08-03 20:20 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/preserveSymlinks.md
> +Isto é para refletir a mesma flag do Node.js; que não resolve o caminho real de links simbólicos.
```suggestion
Esta opção serve para refletir a mesma flag do Node.js; que não resolve o caminho real de links simbólicos.
```

2020-08-03 20:21 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/preserveSymlinks.md
> +Com isto habilitado, as referências para módulos e pacotes (p. ex. diretivas `import` e `/// <reference type="..." />`) são todas resolvidas em relação ao local do arquivo symlink, em vez de relativa
```suggestion
Com esta opção habilitada, as referências para módulos e pacotes (ex. diretivas `import` e `/// <reference type="..." />`) são todas resolvidas em relação ao local do symlink em si, em vez de relativas ao caminho que o symlink resolve.
```

2020-08-03 20:22 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/typeRoots.md
> +Por padrão todos pacotes "`@types`" _visíveis_ são incluídos na sua compilação.
```suggestion
Por padrão todos pacotes `@types` _visíveis_ são incluídos na sua compilação.
```

2020-08-03 20:24 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/types.md
> +Por padrão todos pacotes "`@types`" _visíveis_ são incluídos na sua compilação.
```suggestion
Por padrão todos pacotes `@types` _visíveis_ são incluídos na sua compilação.
```

2020-08-03 20:24 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/types.md
> +Esta característica difere de [`typeRoots`](#typeRoots) , pois serve para especificar somente os tipos exatos a serem incluídos, enquanto [`typeRoots`](#typeRoots) permite que você defina diretórios
```suggestion
Esta opção difere de [`typeRoots`](#typeRoots), pois serve para especificar somente os tipos exatos a serem incluídos, enquanto [`typeRoots`](#typeRoots) permite que você defina diretórios específicos.
```

2020-08-03 20:25 UTC, khaosdoctor requested changes
Small changes

2020-08-04 11:06 UTC, orta commented
Rock, thanks

2020-08-04 11:06 UTC, merged