[PT-BR] include.md, jsxFragmentFactory.md and strictNullChecks.md
microsoft/TypeScript-Website pull request #887
Opened 2020-08-11 13:26 UTC by hmartiins

I translated the following files from the tsconfig session: 

- include.md; 
- jsxFragmentFactory.md;
- strictNullChecks.md.

@orta @khaosdoctor @alvarocamillont @danilofuchs

2020-08-14 14:07 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/jsxFragmentFactory.md
> +oneline: "Faz alguma coisa"
@orta is this a TODO?

2020-08-14 14:19 UTC, khaosdoctor requested changes

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/jsxFragmentFactory.md
> +Especifique a função de fábrica de fragmentos JSX para ser acionada ao direcionar o react JSX emitir com a opção do compilador `jsxFactory` especificada, por exemplo `Fragment`.
```suggestion
Especifique a função que será a fábrica de fragmentos JSX para ser acionada ao usar o react JSX com a opção do compilador `jsxFactory` especificada, por exemplo `Fragment`.
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/jsxFragmentFactory.md
> +Esta opção pode ser usada como base por arquivo um muito semelhante a [Babel's `/** @jsxFrag h */` directive](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#fragments).
```suggestion
Esta opção pode ser usada por arquivo, muito semelhante a [diretiva `/** @jsxFrag h */` do Babel](https://babeljs.io/docs/en/babel-plugin-transform-react-jsx#fragments).
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +display: "Strict Null Checks"
```suggestion
display: "Checagem estrita de nulos"
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +oneline: "Certifique-se de que a nulidade é respeitada no verificador de tipo"
```suggestion
oneline: "Certifique-se de que a nulidade é respeitada ao se verificar os tipos"
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +Quando `strictNullChecks` é `false`, `null` e `undefined` são efetivamentes ignorados pela linguagem. Isso pode levar a erros inesperados no tempo de execução.
```suggestion
Quando `strictNullChecks` é `false`, `null` e `undefined` são efetivamentes ignorados pela linguagem. Isso pode levar a erros inesperados em tempo de execução.
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +Por exemplo, com este código TypeScript, `users.find` você não tem garantia de que realmente encontrará um usuário, mas você pode escrever o código como se ele fosse:
```suggestion
Por exemplo, com este código TypeScript, `usuarios.find` não tem garantia de que realmente encontrará um usuário, mas você pode escrever o código como se ele fosse:
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +declare const loggedInUsername: string;
```suggestion
declare const nomeDeUsuarioLogado: string;
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +const loggedInUser = users.find(u => u.name === loggedInUsername);
```suggestion
const usuarioLogado = usuarios.find(u => u.nome === nomeDeUsuarioLogado);
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +console.log(loggedInUser.age);
```suggestion
console.log(usuarioLogado.idade);
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +Configurar `strictNullChecks` para `true` irá gerar um erro de que você não garantiu a existência de `loggingInUser` antes de tentar usá-lo.
```suggestion
Configurar `strictNullChecks` para `true` irá gerar um erro de que você não garantiu a existência de `usuarioLogado` antes de tentar usá-lo.
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +declare const loggedInUsername: string;
```suggestion
declare const nomeDeUsuarioLogado: string;
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +const users = [
```suggestion
const usuarios = [
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +const users = [
```suggestion
const usuarios = [
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +const loggedInUser = users.find(u => u.name === loggedInUsername);
```suggestion
constusuarioLogado = usuarios.find(u => u.nome === nomeDeUsuarioLogado);
```

2020-08-14 14:19 UTC, khaosdoctor commented on packages/tsconfig-reference/copy/pt/options/strictNullChecks.md
> +console.log(loggedInUser.age);
```suggestion
console.log(usuarioLogado.idade);
```

2020-08-14 15:40 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/include.md
> +display: "Include"
```suggestion
display: "Incluir"
```
O `display` é um texto que facilita encontrar flags ao dar ctrl+F no site. Devem ser traduzidas também!

2020-08-14 15:40 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/jsxFragmentFactory.md
> +display: "jsxFragmentFactory"
```suggestion
display: "Fábrica de fragmentos JSX"
```

2020-08-17 14:23 UTC, khaosdoctor commented
ping @hmartiins

2020-08-27 20:52 UTC, khaosdoctor commented
I think this PR might have staled. @hmartiins are you still with us?

2020-08-30 00:10 UTC, hmartiins commented
yes I am yes, I apologize for the delay, I really hadn't seen your ping, I will review this pull request, I apologize again for the delay

2020-08-31 14:02 UTC, khaosdoctor approved these changes
lgtm

2020-08-31 14:02 UTC, khaosdoctor commented
No problems! Just to keep up to date 😄

2020-08-31 14:02 UTC, khaosdoctor commented
lgtm

2020-08-31 14:03 UTC, merged