[PT-BR] noImplicityAny.md, noImplicityReturns.md, noImplicityThis.md and noImplicityUseStrict.md
microsoft/TypeScript-Website pull request #891
Opened 2020-08-12 01:05 UTC by FelipeBit

@khaosdoctor, @alvarocamillont, @danilofuchs e @orta.

2020-08-12 01:23 UTC, alvarocamillont requested changes

2020-08-12 01:23 UTC, alvarocamillont commented on packages/tsconfig-reference/copy/pt/options/noImplicitThis.md
> +oneline: "Emite erros quando 'this' poderia ser qualquer um"
Emite erro nas expressões 'this' com tipo 'any' implícito.

2020-08-12 11:11 UTC, alvarocamillont approved these changes

2020-08-12 11:12 UTC, alvarocamillont approved these changes

2020-08-12 14:25 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/noImplicitReturns.md
> +function ProcurarFabricanteDeFonesDeOuvido(cor: "azul" | "preto"): string {
```suggestion
function procurarFabricanteDeFonesDeOuvido(cor: "azul" | "preto"): string {
```
Manter consistência com outros exemplos de código que usam camelCase

2020-08-12 14:25 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/noImplicitThis.md
> +Por exemplo, a classe abaixo retorna uma função que tenta acessar `this.largura` e `this.area` – mas o contexto para `this` dentro da função dentro de `funcaoObterArea` não é a instância do Retângulo
```suggestion
Por exemplo, a classe abaixo retorna uma função que tenta acessar `this.largura` e `this.area` – mas o contexto para `this` dentro da função dentro de `funcaoObterArea` não é a instância de `Retangulo`.
```

2020-08-12 15:32 UTC, FelipeBit commented on packages/tsconfig-reference/copy/pt/options/noImplicitReturns.md
> +function ProcurarFabricanteDeFonesDeOuvido(cor: "azul" | "preto"): string {
Corrigido.

2020-08-12 15:32 UTC, FelipeBit commented on packages/tsconfig-reference/copy/pt/options/noImplicitThis.md
> +Por exemplo, a classe abaixo retorna uma função que tenta acessar `this.largura` e `this.area` – mas o contexto para `this` dentro da função dentro de `funcaoObterArea` não é a instância do Retângulo
Corrigido.

2020-08-14 11:58 UTC, orta commented
Looks like all feedback was addressed to me, thanks!

2020-08-14 11:58 UTC, merged