[PT-BR] noLib.md, NoResolve.md, noStrictGenericChecks.md, noUnusedLocals.md and noUnusedParameters.md.
microsoft/TypeScript-Website pull request #925
Opened 2020-08-18 01:29 UTC by FelipeBit

@khaosdoctor, @alvarocamillont, @danilofuchs and @orta .

2020-08-18 05:03 UTC, danilofuchs requested changes

2020-08-18 05:03 UTC, danilofuchs commented on packages/tsconfig-reference/copy/pt/options/noUnusedParameters.md
> +Reporta erros em parêmetros não utilizados em funções.
```suggestion
Reporta erros em parâmetros não utilizados em funções.
```

2020-08-18 14:42 UTC, danilofuchs commented
LGTM

2020-08-18 14:42 UTC, merged

2020-08-20 17:43 UTC, khaosdoctor commented
@FelipeBit Please update the spreadsheet on #233 so we know you finished :)