feat: translate Docs to PT-BR
microsoft/TypeScript-Website pull request #932
Opened 2020-08-18 20:45 UTC by developerfred

#233 

## docs
* [x]  [`Nightly Builds.md`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//documentation/copy/en/Nightly%20Builds.md)
* [x]  [`Creating DTS files From JS.md`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//documentation/copy/en/javascript/Creating%20DTS%20files%20From%20JS.md)
* [x]  [`Intro to JS with TS.md`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//documentation/copy/en/javascript/Intro%20to%20JS%20with%20TS.md)
* [x]  [`React.md`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//documentation/copy/en/tutorials/React.md)
* [x]  [`TypeScript Tooling in 5 minutes.md`](https://github.com/microsoft/TypeScript-Website/blob/v2/packages//documentation/copy/en/tutorials/TypeScript%20Tooling%20in%205%20minutes.md)

2020-08-18 20:54 UTC, orta commented
This is the first PR to add any handbook translations, so you might get me pushing changes in this PR adding CI infra stuff

2020-08-18 21:06 UTC, developerfred commented
> This is the first PR to add any handbook translations, so you might get me pushing changes in this PR adding CI infra stuff

ok, but you can give me the list of files that I do the translation.

2020-08-27 20:50 UTC, danilofuchs requested changes
Great job!
I have some suggestions

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/Nightly Builds.md
> +Veja como você pode obtê-lo e usá-lo com suas ferramentas.
```suggestion
Uma compilação noturna da branch [`master` do TypeScript](https://github.com/Microsoft/TypeScript/tree/master) é publicada à meia-noite PST no npm.
Veja como você pode obtê-la e usá-la com suas ferramentas.
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/Nightly Builds.md
> +A construção noturna atualmente não inclui a configuração completa do plug-in, mas estamos trabalhando na publicação de um instalador todas as noites também.
```suggestion
A compilação noturna atualmente não inclui a configuração completa do plug-in, mas estamos trabalhando na publicação de um instalador todas as noites também.
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/Nightly Builds.md
> +1. Download the [VSDevMode.ps1](https://github.com/Microsoft/TypeScript/blob/master/scripts/VSDevMode.ps1) script.
```suggestion
1. Baixe o script [VSDevMode.ps1](https://github.com/Microsoft/TypeScript/blob/master/scripts/VSDevMode.ps1).
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/javascript/Intro to JS with TS.md
> +- Digitação incremental em JavaScript [via JSDoc](/docs/handbook/jsdoc-supported-types.html)
```suggestion
- Tipagem incremental em JavaScript [via JSDoc](/docs/handbook/jsdoc-supported-types.html)
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/javascript/Intro to JS with TS.md
> +A [home](/) possui uma lista de editores que possuem plugins TypeScript.
```suggestion
A [página inicial](/) possui uma lista de editores que possuem plugins TypeScript.
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/javascript/Intro to JS with TS.md
> +Você pode encontrar a lista completa de padrões JSDoc suportados [em JSDoc Supported Types](/docs/handbook/jsdoc-supported-types.html).
```suggestion
Você pode encontrar a lista completa de padrões JSDoc suportados [em tipos suportados de JSDoc](/docs/handbook/jsdoc-supported-types.html).
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/javascript/Intro to JS with TS.md
> +Para saber mais sobre como o JavaScript é interpretado pelo TypeScript, leia [How TS Type Checks JS](/docs/handbook/type-checking-javascript-files.html)
```suggestion
Para saber mais sobre como o JavaScript é interpretado pelo TypeScript, leia [Como TS Checa tipos de JS](/docs/handbook/type-checking-javascript-files.html)
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +Essa configuração significa que você pode ter a experiência de editor de editores habilitados para TypeScript sem portar seu projeto para TypeScript ou ter que manter arquivos .d.ts em sua base de có
```suggestion
Essa configuração significa que você pode ter a experiência de editores habilitados para TypeScript sem portar seu projeto para TypeScript ou ter que manter arquivos .d.ts em sua base de código.
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +  // Change this to match your project
```suggestion
  // Mude isso para corresponder ao seu projeto
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +    // normally they are ignored as source files
```suggestion
    // Diz para o TypeScript ler arquivos JS.
    // Normalmente, seriam ignorados como arquivos fonte
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +    // Generate d.ts files
```suggestion
    // Gerar arquivos d.ts
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +    // only output d.ts files
```suggestion
    // A compilação só gerará arquivos
    // d.ts na saída
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +    // next to the .js files
```suggestion
    // Tipos devem ir neste diretório.
    // Remover isso colocará arquivos .d.ts
    // ao lado dos arquivos .js
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +TypeScript replica a resolução do nó para módulos em um `package.json`, com uma etapa adicional para localizar arquivos `.d.ts`.
```suggestion
TypeScript replica a resolução do Node para módulos em um `package.json`, com uma etapa adicional para localizar arquivos `.d.ts`.
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +| "types": "./dist/main.js" | ./main/main.d.ts               |
```suggestion
| Package.json              | Localização padrão do .d.ts      |
| :------------------------ | :----------------------------- |
| Sem campo "types"         | Checa "main", então index.d.ts |
| "types": "main.d.ts"      | main.d.ts                      |
| "types": "./dist/main.js" | ./main/main.d.ts               |
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +If absent, then "main" is used
```suggestion
Se estiver ausente, "main" é usado
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/release-notes/Creating DTS files From JS.md
> +| "main":"./dist/index.js" | ./dist/index.d.ts         |
```suggestion
| Package.json             | Localização padrão do .d.ts |
| :----------------------- | :------------------------ |
| Sem campo "main"         | index.d.ts                |
| "main":"index.js"        | index.d.ts                |
| "main":"./dist/index.js" | ./dist/index.d.ts         |
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/tutorials/TypeScript Tooling in 5 minutes.md
> +Podemos tentar alterar o saudador de chamada para passar uma matriz em vez disso:
```suggestion
As anotações de tipo no TypeScript são maneiras leves de registrar o contrato pretendido da função ou variável.
Neste caso, pretendemos que a função greeter seja chamada com um único parâmetro de string.
Podemos tentar alterar a chamada de greeter para passar uma matriz em vez disso:
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/tutorials/TypeScript Tooling in 5 minutes.md
> +Da mesma forma, tente remover todos os argumentos para a chamada de saudação.
```suggestion
Da mesma forma, tente remover todos os argumentos para a chamada de greeter.
```

2020-08-27 20:50 UTC, danilofuchs commented on packages/documentation/copy/pt/tutorials/TypeScript Tooling in 5 minutes.md
> +Coloque o cursor sobre a referência da função saudação e pressione F12 para ir para sua definição.
```suggestion
Coloque o cursor sobre a referência da função greeter e pressione F12 para ir para sua definição.
```

2020-08-28 14:41 UTC, danilofuchs commented on packages/documentation/copy/pt/javascript/Intro to JS with TS.md
> +Você pode encontrar a lista completa de padrões JSDoc suportados [em JSDoc Supported Types](/docs/handbook/jsdoc-supported-types.html).
Please translate this phrase

2020-08-28 14:42 UTC, danilofuchs commented on packages/documentation/copy/pt/javascript/Intro to JS with TS.md
> +Para saber mais sobre como o JavaScript é interpretado pelo TypeScript, leia [How TS Type Checks JS](/docs/handbook/type-checking-javascript-files.html)
Here as well. These are shown as-is, with hyperlinks, so the user must have the information in Portuguese

2020-08-28 14:43 UTC, danilofuchs commented
@developerfred I believe you forgot to update some parts. 

Expand the 'hidden conversations' part to reveal the other suggestions:
![image](https://user-images.githubusercontent.com/17657014/91580539-a3d51780-e923-11ea-9dca-32dae11d6259.png)

2020-08-28 22:28 UTC, developerfred commented
> @developerfred I believe you forgot to update some parts.
> 
> Expand the 'hidden conversations' part to reveal the other suggestions:
> ![image](https://user-images.githubusercontent.com/17657014/91580539-a3d51780-e923-11ea-9dca-32dae11d6259.png)

Thanks! ✅

2020-09-03 20:10 UTC, danilofuchs commented
LGTM

2020-09-08 15:53 UTC, orta commented
I've rebased this, lets hope it fixes CI

2020-09-08 21:41 UTC, khaosdoctor commented
CI is Fixed!

2020-09-08 21:42 UTC, khaosdoctor approved these changes
LGTM

2020-09-08 21:42 UTC, khaosdoctor commented
LGTM

2020-09-08 22:09 UTC, khaosdoctor commented
@orta Either the bot is not working, or the file is not in my scope

2020-09-09 14:42 UTC, orta commented
Yeah, I'm bad with rebases it seems

2020-09-09 14:42 UTC, merged