Translate 3 tsconfig files to ja
microsoft/TypeScript-Website pull request #978
Opened 2020-08-27 15:09 UTC by harapeko

Part of #220 

- [ ] [intro.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/intro.md)
- [ ] [Watch_Options_999.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/categories/Watch_Options_999.md)
- [ ] [fallbackPolling.md](https://github.com/microsoft/TypeScript-Website/blob/v2/packages/tsconfig-reference/copy/en/options/fallbackPolling.md)

2020-09-02 20:48 UTC, harapeko commented
レビューおねがいします！
@sasurau4, @Quramy, @Naturalclar, and @Takepepe

@Takepepe さんは @takefumi-yoshii さんにIDが変更されたのでしょうか？
そうであれば、`.github/CODEOWNERS` の方も更新しておいたほうが良さそうです

2020-09-16 12:39 UTC, sasurau4 reviewed
コメントしました :+1:

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/intro.md
> +このページは TSConfig ファイルで利用できるフラグを余す所なくカバーしています。このページは、フラグ毎の概要から始まり、JSON ファイルのルート属性、オプションの大部分を占める `compilerOptions` へと至り、`watchOptions` で締めくくります。
IMO: あまり「至り」みたいな言い方をしない気がするので言い換えてみました。あまりこなれてないかもしれないです。
```suggestion
このページは TSConfig ファイルで利用できるフラグを余す所なくカバーしています。このページは、フラグ毎の概要から始まり、JSON ファイルのルート属性、オプションの大部分を占める `compilerOptions` を説明し、最後は `watchOptions` で締めくくられます。
```

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/categories/Watch_Options_999.md
> +TypeScript 3.8 ディレクトリを監視するための新戦略を打ち出しました。これは、`node_modules` の変更を効率的に拾うために極めて重要なものです。
IMO: 
```suggestion
TypeScript 3.8 にてディレクトリを監視するための新戦略をリリースしました。これは、`node_modules` の変更を効率的に検知するために極めて重要なものです。
```

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/categories/Watch_Options_999.md
> +各プロジェクトは異なる戦略の下でうまく動作するものかもしれませんし、この新しいアプローチが一連の作業の流れでうまく動作しないかもしれません。なので、TypeScript 3.8 では新しく `watchOptions` フィールドが導入されました。このフィールドでは、ファイルやディレクトリを追跡する為に、どの監視戦略を使用すべきか、コンパイラと言語のサービスに伝えることができます。
language serviceはtypescriptの持つ特定機能を指す言葉なので訳さずにそのまま残しておくのが良さそうです。
```suggestion
各プロジェクトは異なる戦略の下でより良く動作する可能性もあり、逆にこの新しいアプローチが一連の作業の流れでうまく動作しない可能性もあります。そのため、TypeScript 3.8 では新しく `watchOptions` フィールドが導入されました。このフィールドでは、ファイルやディレクトリを追跡する為に、どの監視戦略を使用すべきか、compiler/language serviceに伝えることができます。
```

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +oneline: "システムがネイティブのファイルウォッチャーを使い切ったら、ウォッチャー使うべきもの"
displayとonelineはあとでまとめてやろうということで全部残したままにしてあるので、一旦訳さなくても大丈夫です :+1:

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +ファイルシステムのイベントを使用している時、システムがネイティブのファイルウォッチャーを使い切ったり、ネイティブのファイルウォッチャーが対応していない場合、どのようなポーリング戦略を行使するかを指定するオプションです。
IMO
```suggestion
ファイルシステムのイベントを使用するときに、システムがネイティブのファイルウォッチャーを使い切ったり、ネイティブのファイルウォッチャーが対応していない場合、どのようなポーリング戦略を行使するかを指定するオプションです。
```

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +- `priorityPollingInterval`: 1 秒間に数回、全ファイルをチェックします。しかし、特定の種類のファイルにはヒューリスティックを使用して、他ファイルよりも低頻度でチェックします。
ヒューリスティックってどうやって訳すのがいいのか迷いますね
とりあえず、Wikipediaから持ってきました
https://ja.wikipedia.org/wiki/%E3%83%92%E3%83%A5%E3%83%BC%E3%83%AA%E3%82%B9%E3%83%86%E3%82%A3%E3%82%AF%E3%82%B9
```suggestion
- `priorityPollingInterval`: 1 秒間に数回、全ファイルをチェックします。しかし、特定の種類のファイルには発見的手法を使用して、他ファイルよりも低頻度でチェックします。
```

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +- `dynamicPriorityPolling`: 変更頻度の少ないファイルは、低頻度でチェックされるように動的キューを使用します。
IMO
```suggestion
- `dynamicPriorityPolling`: 変更頻度の少ないファイルは、他よりも低頻度でチェックされるように動的キューを使用します。
```

2020-09-16 12:39 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +- `synchronousWatchDirectory`: ディレクトリの遅延監視を無効にします。遅延監視は、沢山のファイル変更が一度に引き起こされる場合に有効です(例： `npm install` 実行による `node_modules` の変更)。しかし、このフラグは余り一般的でないセットアップの為にあるので、無効にしておくのが良いでしょう。
最後の文の意味が逆だと思われます。一般的にはonにしておいて必要に応じてoffにもできるという意味だと思われるので直訳してみました。直訳すぎてこなれてないのでもっと良い訳があると嬉しいです。
```suggestion
- `synchronousWatchDirectory`: ディレクトリの遅延監視を無効にします。遅延監視は、沢山のファイル変更が一度に引き起こされる場合に有効です(例： `npm install` 実行による `node_modules` の変更)。しかし、あまり一般的でないセットアップの為に、このフラグで遅延監視機能を無効にしたくなることもあるかもしれません。
```

2020-09-30 15:45 UTC, harapeko commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +oneline: "システムがネイティブのファイルウォッチャーを使い切ったら、ウォッチャー使うべきもの"
- Watch_Options_999.md
- fallbackPolling.md
両方をもとに戻しました！

2020-09-30 16:15 UTC, harapeko commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +- `priorityPollingInterval`: 1 秒間に数回、全ファイルをチェックします。しかし、特定の種類のファイルにはヒューリスティックを使用して、他ファイルよりも低頻度でチェックします。
ここ悩みました！取り込みました

2020-09-30 16:17 UTC, harapeko commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +- `synchronousWatchDirectory`: ディレクトリの遅延監視を無効にします。遅延監視は、沢山のファイル変更が一度に引き起こされる場合に有効です(例： `npm install` 実行による `node_modules` の変更)。しかし、このフラグは余り一般的でないセットアップの為にあるので、無効にしておくのが良いでしょう。
次のように修正してみました！
https://github.com/microsoft/TypeScript-Website/pull/978/commits/5f4d0509f38bc3b952fda817c0fa0e2c9b00e0e4

2020-09-30 16:41 UTC, harapeko commented
@sasurau4, @Quramy, @Naturalclar
2回目のレビュー依頼になります。

作業内容
- Suggestion取り込んだ
- displayとonelineを元に戻した(後から一気に対応できるように)
- `synchronousWatchDirectory` の訳を洗練しました

よろしくお願いします！

2020-10-05 01:03 UTC, sasurau4 requested changes
1点だけ 🙏

2020-10-05 01:03 UTC, sasurau4 commented on packages/tsconfig-reference/copy/ja/options/fallbackPolling.md
> +- `synchronousWatchDirectory`: ディレクトリの遅延監視を無効にします。遅延監視機能は、沢山のファイル変更が一度に引き起こされる場合に役に立ちますが(例： `npm install` 実行 `node_modules` の変更)、余り一般的な構成ではないので、この遅延監視フラグを無効にしたい事があるかもしれません。
```suggestion
- `synchronousWatchDirectory`: ディレクトリの遅延監視を無効にします。遅延監視機能は、沢山のファイル変更が一度に引き起こされる場合に役に立ちますが(例： `npm install` による `node_modules` の変更)、あまり一般的な構成ではないときに、この遅延監視フラグを無効にしたくなるかもしれません。
```

2020-10-09 18:45 UTC, harapeko commented
@sasurau4, @Quramy, @Naturalclar
再レビュー依頼になります。

- 頂いた1点のSuggestionを取り込みました
- 同オプションの訳を改善しました(少し違和感を感じたため)

何度も日が空いてしまい、大変お手数おかけ致しますがよろしくお願いいたします。

2020-10-15 07:18 UTC, sasurau4 approved these changes
めっちゃ長くなってしまいましたが、ありがとうございました！ 👍 

LGTM

2020-10-19 05:30 UTC, harapeko commented
感謝です>w<ノ

2020-10-20 11:28 UTC, sasurau4 commented
@orta Codeowners merging workflow failed because of unhandled promise rejection. Could you investigate it?
https://github.com/microsoft/TypeScript-Website/pull/978/checks?check_run_id=1257687413

2020-10-21 16:18 UTC, orta commented
Thanks @sasurau4 - I'll merge this for now and look 👍🏻

2020-10-21 16:18 UTC, merged